import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Textarea } from '../ui/textarea';
import { Badge } from '../ui/badge';
import { Switch } from '../ui/switch';
import { 
  Dialog, 
  DialogContent, 
  DialogDescription,
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
  DialogFooter
} from '../ui/dialog';
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from '../ui/table';
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '../ui/select';
import { 
  Plus, 
  Edit, 
  Trash2, 
  RefreshCw, 
  Calendar,
  Target,
  Users,
  Clock,
  Check,
  X,
  Sparkles
} from 'lucide-react';
import { toast } from 'sonner';

interface DailyChallenge {
  id: string;
  title: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: 'photography' | 'maintenance' | 'community' | 'knowledge' | 'adventure';
  isActive: boolean;
  dateCreated: string;
  autoGenerated: boolean;
  participantCount: number;
  completionRate: number;
  expiresAt: string;
}

export function AdminDailyChallengesPage() {
  const [challenges, setChallenges] = useState<DailyChallenge[]>([
    {
      id: '1',
      title: 'Show Your Car\'s Cozy Corner',
      description: '🚗 Show us your car\'s cozy corner; what\'s the comfiest spot in your ride that makes every drive feel like a mini adventure? 🛣️',
      difficulty: 'easy',
      category: 'photography',
      isActive: true,
      dateCreated: '2024-03-15',
      autoGenerated: true,
      participantCount: 156,
      completionRate: 87,
      expiresAt: '2024-03-16'
    },
    {
      id: '2',
      title: 'Engine Bay Photo Challenge',
      description: 'Take a clean, detailed photo of your engine bay and share one maintenance tip that keeps it running smoothly!',
      difficulty: 'medium',
      category: 'maintenance',
      isActive: true,
      dateCreated: '2024-03-15',
      autoGenerated: true,
      participantCount: 89,
      completionRate: 72,
      expiresAt: '2024-03-16'
    },
    {
      id: '3',
      title: 'Car Brand Knowledge Quiz',
      description: 'Test your knowledge! Name 3 Chinese car brands that have hybrid models available in the UAE market.',
      difficulty: 'medium',
      category: 'knowledge',
      isActive: true,
      dateCreated: '2024-03-15',
      autoGenerated: true,
      participantCount: 234,
      completionRate: 65,
      expiresAt: '2024-03-16'
    },
    {
      id: '4',
      title: 'Community Help Challenge',
      description: 'Help a fellow community member by answering their question or sharing helpful advice on any car-related topic.',
      difficulty: 'easy',
      category: 'community',
      isActive: true,
      dateCreated: '2024-03-15',
      autoGenerated: true,
      participantCount: 178,
      completionRate: 91,
      expiresAt: '2024-03-16'
    },
    {
      id: '5',
      title: 'Share Your Driving Route',
      description: 'Share a photo or description of your favorite driving route in the UAE and explain why it\'s special to you.',
      difficulty: 'easy',
      category: 'adventure',
      isActive: true,
      dateCreated: '2024-03-15',
      autoGenerated: true,
      participantCount: 145,
      completionRate: 78,
      expiresAt: '2024-03-16'
    }
  ]);

  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [editingChallenge, setEditingChallenge] = useState<DailyChallenge | null>(null);
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    difficulty: 'easy' as const,
    category: 'photography' as const,
    isActive: true
  });

  // Auto-generated challenge templates
  const challengeTemplates = [
    {
      title: 'Weekly Maintenance Check',
      description: 'Share a photo of you performing a basic maintenance check on your car (oil, tires, lights, etc.)',
      difficulty: 'easy' as const,
      category: 'maintenance' as const
    },
    {
      title: 'Scenic Drive Sunday',
      description: 'Take your car on a scenic drive and share the most beautiful view you encountered',
      difficulty: 'easy' as const,
      category: 'adventure' as const
    },
    {
      title: 'Car Interior Details',
      description: 'Show off your car\'s interior features that make your daily commute more comfortable',
      difficulty: 'easy' as const,
      category: 'photography' as const
    },
    {
      title: 'Help a Fellow Driver',
      description: 'Answer a question from another community member or share a helpful driving tip',
      difficulty: 'easy' as const,
      category: 'community' as const
    },
    {
      title: 'Car Technology Feature',
      description: 'Demonstrate or explain a technology feature in your car that you find most useful',
      difficulty: 'medium' as const,
      category: 'knowledge' as const
    },
    {
      title: 'Fuel Efficiency Challenge',
      description: 'Share your car\'s fuel efficiency stats and tips on how you achieve the best mileage',
      difficulty: 'medium' as const,
      category: 'knowledge' as const
    },
    {
      title: 'Car Wash Wednesday',
      description: 'Share before and after photos of washing your car, include your favorite car care products',
      difficulty: 'easy' as const,
      category: 'maintenance' as const
    },
    {
      title: 'Dashboard Photography',
      description: 'Take an artistic photo of your car\'s dashboard highlighting your favorite features',
      difficulty: 'easy' as const,
      category: 'photography' as const
    },
    {
      title: 'Road Trip Planning',
      description: 'Plan and share a perfect weekend road trip route within the UAE, including stops and attractions',
      difficulty: 'medium' as const,
      category: 'adventure' as const
    },
    {
      title: 'Car Safety Feature Spotlight',
      description: 'Highlight and explain a safety feature in your car that gives you confidence while driving',
      difficulty: 'easy' as const,
      category: 'knowledge' as const
    }
  ];

  const generateDailyChallenges = () => {
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    
    // Select 10 random templates
    const shuffled = [...challengeTemplates].sort(() => 0.5 - Math.random());
    const selectedTemplates = shuffled.slice(0, 10);
    
    const newChallenges = selectedTemplates.map((template, index) => ({
      id: `auto_${Date.now()}_${index}`,
      title: template.title,
      description: template.description,
      difficulty: template.difficulty,
      category: template.category,
      isActive: true,
      dateCreated: today.toISOString().split('T')[0],
      autoGenerated: true,
      participantCount: 0,
      completionRate: 0,
      expiresAt: tomorrow.toISOString().split('T')[0]
    }));

    // Replace existing auto-generated challenges
    const manualChallenges = challenges.filter(c => !c.autoGenerated);
    setChallenges([...manualChallenges, ...newChallenges]);
    
    toast.success(`Generated ${newChallenges.length} new daily challenges!`);
  };

  const handleCreateChallenge = () => {
    if (!formData.title.trim() || !formData.description.trim()) {
      toast.error('Please fill in all required fields');
      return;
    }

    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    const newChallenge: DailyChallenge = {
      id: `manual_${Date.now()}`,
      title: formData.title,
      description: formData.description,
      difficulty: formData.difficulty,
      category: formData.category,
      isActive: formData.isActive,
      dateCreated: today.toISOString().split('T')[0],
      autoGenerated: false,
      participantCount: 0,
      completionRate: 0,
      expiresAt: tomorrow.toISOString().split('T')[0]
    };

    setChallenges([newChallenge, ...challenges]);
    setFormData({
      title: '',
      description: '',
      difficulty: 'easy',
      category: 'photography',
      isActive: true
    });
    setIsCreateDialogOpen(false);
    toast.success('Challenge created successfully!');
  };

  const handleEditChallenge = () => {
    if (!editingChallenge || !formData.title.trim() || !formData.description.trim()) {
      toast.error('Please fill in all required fields');
      return;
    }

    const updatedChallenges = challenges.map(challenge =>
      challenge.id === editingChallenge.id
        ? {
            ...challenge,
            title: formData.title,
            description: formData.description,
            difficulty: formData.difficulty,
            category: formData.category,
            isActive: formData.isActive
          }
        : challenge
    );

    setChallenges(updatedChallenges);
    setIsEditDialogOpen(false);
    setEditingChallenge(null);
    toast.success('Challenge updated successfully!');
  };

  const handleDeleteChallenge = (id: string) => {
    setChallenges(challenges.filter(challenge => challenge.id !== id));
    toast.success('Challenge deleted successfully!');
  };

  const openEditDialog = (challenge: DailyChallenge) => {
    setEditingChallenge(challenge);
    setFormData({
      title: challenge.title,
      description: challenge.description,
      difficulty: challenge.difficulty,
      category: challenge.category,
      isActive: challenge.isActive
    });
    setIsEditDialogOpen(true);
  };

  const toggleChallengeStatus = (id: string) => {
    const updatedChallenges = challenges.map(challenge =>
      challenge.id === id
        ? { ...challenge, isActive: !challenge.isActive }
        : challenge
    );
    setChallenges(updatedChallenges);
    toast.success('Challenge status updated!');
  };

  const getDifficultyBadgeColor = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return 'bg-green-500/10 text-green-500';
      case 'medium': return 'bg-yellow-500/10 text-yellow-500';
      case 'hard': return 'bg-red-500/10 text-red-500';
      default: return 'bg-gray-500/10 text-gray-500';
    }
  };

  const getCategoryBadgeColor = (category: string) => {
    switch (category) {
      case 'photography': return 'bg-purple-500/10 text-purple-500';
      case 'maintenance': return 'bg-blue-500/10 text-blue-500';
      case 'community': return 'bg-green-500/10 text-green-500';
      case 'knowledge': return 'bg-orange-500/10 text-orange-500';
      case 'adventure': return 'bg-red-500/10 text-red-500';
      default: return 'bg-gray-500/10 text-gray-500';
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-[var(--sublimes-light-text)]">Daily Challenges</h1>
          <p className="text-gray-400">Manage community daily challenges and engagement activities</p>
        </div>
        <div className="flex gap-3">
          <Button
            onClick={generateDailyChallenges}
            className="bg-[var(--sublimes-blue-gradient-start)] hover:bg-[var(--sublimes-blue-gradient-end)] text-white"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Generate Daily Challenges
          </Button>
          <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
            <DialogTrigger asChild>
              <Button className="bg-[var(--sublimes-gold)] text-black hover:bg-[var(--sublimes-gold)]/80">
                <Plus className="w-4 h-4 mr-2" />
                Create Challenge
              </Button>
            </DialogTrigger>
            <DialogContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
              <DialogHeader>
                <DialogTitle className="text-[var(--sublimes-light-text)]">Create New Challenge</DialogTitle>
                <DialogDescription className="text-gray-400">
                  Create a new daily challenge for the community
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                    Challenge Title
                  </label>
                  <Input
                    placeholder="Enter challenge title..."
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                    Description
                  </label>
                  <Textarea
                    placeholder="Describe the challenge..."
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)] min-h-[100px]"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                      Difficulty
                    </label>
                    <Select value={formData.difficulty} onValueChange={(value: any) => setFormData({ ...formData, difficulty: value })}>
                      <SelectTrigger className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
                        <SelectItem value="easy">Easy</SelectItem>
                        <SelectItem value="medium">Medium</SelectItem>
                        <SelectItem value="hard">Hard</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                      Category
                    </label>
                    <Select value={formData.category} onValueChange={(value: any) => setFormData({ ...formData, category: value })}>
                      <SelectTrigger className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
                        <SelectItem value="photography">Photography</SelectItem>
                        <SelectItem value="maintenance">Maintenance</SelectItem>
                        <SelectItem value="community">Community</SelectItem>
                        <SelectItem value="knowledge">Knowledge</SelectItem>
                        <SelectItem value="adventure">Adventure</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <Switch
                    checked={formData.isActive}
                    onCheckedChange={(checked) => setFormData({ ...formData, isActive: checked })}
                  />
                  <label className="text-sm text-[var(--sublimes-light-text)]">
                    Activate immediately
                  </label>
                </div>
              </div>
              <DialogFooter>
                <Button
                  variant="outline"
                  onClick={() => setIsCreateDialogOpen(false)}
                  className="border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]"
                >
                  Cancel
                </Button>
                <Button
                  onClick={handleCreateChallenge}
                  className="bg-[var(--sublimes-gold)] text-black hover:bg-[var(--sublimes-gold)]/80"
                >
                  Create Challenge
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-400">Active Challenges</p>
                <p className="text-2xl font-bold text-[var(--sublimes-light-text)]">
                  {challenges.filter(c => c.isActive).length}
                </p>
              </div>
              <div className="w-8 h-8 bg-green-500/10 rounded-lg flex items-center justify-center">
                <Target className="w-4 h-4 text-green-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-400">Total Participants</p>
                <p className="text-2xl font-bold text-[var(--sublimes-light-text)]">
                  {challenges.reduce((sum, c) => sum + c.participantCount, 0)}
                </p>
              </div>
              <div className="w-8 h-8 bg-blue-500/10 rounded-lg flex items-center justify-center">
                <Users className="w-4 h-4 text-blue-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-400">Avg Completion Rate</p>
                <p className="text-2xl font-bold text-[var(--sublimes-light-text)]">
                  {challenges.length > 0 ? Math.round(challenges.reduce((sum, c) => sum + c.completionRate, 0) / challenges.length) : 0}%
                </p>
              </div>
              <div className="w-8 h-8 bg-[var(--sublimes-gold)]/10 rounded-lg flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-[var(--sublimes-gold)]" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-400">Auto Generated</p>
                <p className="text-2xl font-bold text-[var(--sublimes-light-text)]">
                  {challenges.filter(c => c.autoGenerated).length}
                </p>
              </div>
              <div className="w-8 h-8 bg-purple-500/10 rounded-lg flex items-center justify-center">
                <RefreshCw className="w-4 h-4 text-purple-500" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Challenges Table */}
      <Card className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
        <CardHeader>
          <CardTitle className="text-[var(--sublimes-light-text)]">All Challenges</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow className="border-[var(--sublimes-border)]">
                <TableHead className="text-gray-400">Challenge</TableHead>
                <TableHead className="text-gray-400">Difficulty</TableHead>
                <TableHead className="text-gray-400">Category</TableHead>
                <TableHead className="text-gray-400">Status</TableHead>
                <TableHead className="text-gray-400">Participants</TableHead>
                <TableHead className="text-gray-400">Completion</TableHead>
                <TableHead className="text-gray-400">Type</TableHead>
                <TableHead className="text-gray-400">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {challenges.map((challenge) => (
                <TableRow key={challenge.id} className="border-[var(--sublimes-border)]">
                  <TableCell>
                    <div>
                      <p className="font-medium text-[var(--sublimes-light-text)]">{challenge.title}</p>
                      <p className="text-sm text-gray-400 max-w-md truncate">{challenge.description}</p>
                    </div>
                  </TableCell>
                  <TableCell>
                    <Badge className={getDifficultyBadgeColor(challenge.difficulty)}>
                      {challenge.difficulty}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <Badge className={getCategoryBadgeColor(challenge.category)}>
                      {challenge.category}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center space-x-2">
                      <Switch
                        checked={challenge.isActive}
                        onCheckedChange={() => toggleChallengeStatus(challenge.id)}
                      />
                      <span className={`text-sm ${challenge.isActive ? 'text-green-500' : 'text-gray-400'}`}>
                        {challenge.isActive ? 'Active' : 'Inactive'}
                      </span>
                    </div>
                  </TableCell>
                  <TableCell className="text-[var(--sublimes-light-text)]">
                    {challenge.participantCount}
                  </TableCell>
                  <TableCell className="text-[var(--sublimes-light-text)]">
                    {challenge.completionRate}%
                  </TableCell>
                  <TableCell>
                    <Badge className={challenge.autoGenerated ? 'bg-purple-500/10 text-purple-500' : 'bg-blue-500/10 text-blue-500'}>
                      {challenge.autoGenerated ? 'Auto' : 'Manual'}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center space-x-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openEditDialog(challenge)}
                        className="text-gray-400 hover:text-[var(--sublimes-light-text)]"
                      >
                        <Edit className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDeleteChallenge(challenge.id)}
                        className="text-gray-400 hover:text-red-500"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
          <DialogHeader>
            <DialogTitle className="text-[var(--sublimes-light-text)]">Edit Challenge</DialogTitle>
            <DialogDescription className="text-gray-400">
              Modify the challenge details
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                Challenge Title
              </label>
              <Input
                placeholder="Enter challenge title..."
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                Description
              </label>
              <Textarea
                placeholder="Describe the challenge..."
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)] min-h-[100px]"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                  Difficulty
                </label>
                <Select value={formData.difficulty} onValueChange={(value: any) => setFormData({ ...formData, difficulty: value })}>
                  <SelectTrigger className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
                    <SelectItem value="easy">Easy</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="hard">Hard</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="text-sm font-medium text-[var(--sublimes-light-text)] mb-1 block">
                  Category
                </label>
                <Select value={formData.category} onValueChange={(value: any) => setFormData({ ...formData, category: value })}>
                  <SelectTrigger className="bg-[var(--sublimes-dark-bg)] border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-[var(--sublimes-card-bg)] border-[var(--sublimes-border)]">
                    <SelectItem value="photography">Photography</SelectItem>
                    <SelectItem value="maintenance">Maintenance</SelectItem>
                    <SelectItem value="community">Community</SelectItem>
                    <SelectItem value="knowledge">Knowledge</SelectItem>
                    <SelectItem value="adventure">Adventure</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <Switch
                checked={formData.isActive}
                onCheckedChange={(checked) => setFormData({ ...formData, isActive: checked })}
              />
              <label className="text-sm text-[var(--sublimes-light-text)]">
                Active
              </label>
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsEditDialogOpen(false)}
              className="border-[var(--sublimes-border)] text-[var(--sublimes-light-text)]"
            >
              Cancel
            </Button>
            <Button
              onClick={handleEditChallenge}
              className="bg-[var(--sublimes-gold)] text-black hover:bg-[var(--sublimes-gold)]/80"
            >
              Update Challenge
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}