export interface DailyChallenge {
  id: string;
  title: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: 'photography' | 'maintenance' | 'community' | 'knowledge' | 'adventure';
  isActive: boolean;
  dateCreated: string;
  autoGenerated: boolean;
  participantCount: number;
  completionRate: number;
  expiresAt: string;
}

// Default daily challenges that get auto-generated
export const challengeTemplates = [
  {
    title: 'Show Your Car\'s Cozy Corner',
    description: '🚗 Show us your car\'s cozy corner; what\'s the comfiest spot in your ride that makes every drive feel like a mini adventure? 🛣️',
    difficulty: 'easy' as const,
    category: 'photography' as const
  },
  {
    title: 'Weekly Maintenance Check',
    description: 'Share a photo of you performing a basic maintenance check on your car (oil, tires, lights, etc.)',
    difficulty: 'easy' as const,
    category: 'maintenance' as const
  },
  {
    title: 'Scenic Drive Sunday',
    description: 'Take your car on a scenic drive and share the most beautiful view you encountered',
    difficulty: 'easy' as const,
    category: 'adventure' as const
  },
  {
    title: 'Car Interior Details',
    description: 'Show off your car\'s interior features that make your daily commute more comfortable',
    difficulty: 'easy' as const,
    category: 'photography' as const
  },
  {
    title: 'Help a Fellow Driver',
    description: 'Answer a question from another community member or share a helpful driving tip',
    difficulty: 'easy' as const,
    category: 'community' as const
  },
  {
    title: 'Car Technology Feature',
    description: 'Demonstrate or explain a technology feature in your car that you find most useful',
    difficulty: 'medium' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Fuel Efficiency Challenge',
    description: 'Share your car\'s fuel efficiency stats and tips on how you achieve the best mileage',
    difficulty: 'medium' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Car Wash Wednesday',
    description: 'Share before and after photos of washing your car, include your favorite car care products',
    difficulty: 'easy' as const,
    category: 'maintenance' as const
  },
  {
    title: 'Dashboard Photography',
    description: 'Take an artistic photo of your car\'s dashboard highlighting your favorite features',
    difficulty: 'easy' as const,
    category: 'photography' as const
  },
  {
    title: 'Road Trip Planning',
    description: 'Plan and share a perfect weekend road trip route within the UAE, including stops and attractions',
    difficulty: 'medium' as const,
    category: 'adventure' as const
  },
  {
    title: 'Car Safety Feature Spotlight',
    description: 'Highlight and explain a safety feature in your car that gives you confidence while driving',
    difficulty: 'easy' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Engine Bay Clean Up',
    description: 'Clean your engine bay and share the process - what products and techniques work best?',
    difficulty: 'medium' as const,
    category: 'maintenance' as const
  },
  {
    title: 'Night Drive Photography',
    description: 'Capture the beauty of your car during a night drive - city lights, neon reflections, or starry skies',
    difficulty: 'medium' as const,
    category: 'photography' as const
  },
  {
    title: 'Newcomer Welcome',
    description: 'Welcome a new community member and share your best advice for car ownership in the UAE',
    difficulty: 'easy' as const,
    category: 'community' as const
  },
  {
    title: 'Hidden Car Feature',
    description: 'Share a hidden or lesser-known feature in your car that other owners might not know about',
    difficulty: 'medium' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Car Modification Showcase',
    description: 'Show off a modification or upgrade you\'ve made to your car and explain why you chose it',
    difficulty: 'medium' as const,
    category: 'photography' as const
  },
  {
    title: 'Desert Adventure',
    description: 'Share your experience driving in the UAE desert - preparation tips and memorable moments',
    difficulty: 'hard' as const,
    category: 'adventure' as const
  },
  {
    title: 'Tire Care Tuesday',
    description: 'Check your tire pressure and tread depth, share tips for tire maintenance in hot weather',
    difficulty: 'easy' as const,
    category: 'maintenance' as const
  },
  {
    title: 'Car Meetup Organization',
    description: 'Organize or suggest a car meetup location and explain why it would be perfect for the community',
    difficulty: 'medium' as const,
    category: 'community' as const
  },
  {
    title: 'Trunk Organization',
    description: 'Show how you organize your car trunk for maximum efficiency and share your must-have items',
    difficulty: 'easy' as const,
    category: 'photography' as const
  },
  {
    title: 'Electric Vehicle Knowledge',
    description: 'Share facts about electric or hybrid vehicles - charging tips, efficiency tricks, or environmental benefits',
    difficulty: 'medium' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Sunrise/Sunset Car Shot',
    description: 'Capture your car during golden hour - sunrise or sunset for the most dramatic lighting',
    difficulty: 'medium' as const,
    category: 'photography' as const
  },
  {
    title: 'Community Question Answer',
    description: 'Find an unanswered question in the community and provide a detailed, helpful response',
    difficulty: 'easy' as const,
    category: 'community' as const
  },
  {
    title: 'Car Audio System',
    description: 'Share your car\'s audio setup and your favorite driving playlist or music recommendations',
    difficulty: 'easy' as const,
    category: 'knowledge' as const
  },
  {
    title: 'Parking Skills Challenge',
    description: 'Share a photo of your best parking job in a challenging space and offer parking tips',
    difficulty: 'easy' as const,
    category: 'photography' as const
  }
];

// Get today's active challenges
export const getTodaysChallenges = (allChallenges: DailyChallenge[]): DailyChallenge[] => {
  const today = new Date().toISOString().split('T')[0];
  return allChallenges.filter(challenge => 
    challenge.isActive && 
    challenge.dateCreated === today
  ).slice(0, 10); // Limit to 10 challenges per day
};

// Get a random challenge from active ones
export const getRandomChallenge = (allChallenges: DailyChallenge[]): DailyChallenge | null => {
  const activeChallenges = allChallenges.filter(c => c.isActive);
  if (activeChallenges.length === 0) return null;
  
  const randomIndex = Math.floor(Math.random() * activeChallenges.length);
  return activeChallenges[randomIndex];
};

// Generate 10 daily challenges for today
export const generateTodaysChallenges = (): DailyChallenge[] => {
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  // Shuffle templates and select 10
  const shuffled = [...challengeTemplates].sort(() => 0.5 - Math.random());
  const selectedTemplates = shuffled.slice(0, 10);
  
  return selectedTemplates.map((template, index) => ({
    id: `auto_${Date.now()}_${index}`,
    title: template.title,
    description: template.description,
    difficulty: template.difficulty,
    category: template.category,
    isActive: true,
    dateCreated: today.toISOString().split('T')[0],
    autoGenerated: true,
    participantCount: 0,
    completionRate: 0,
    expiresAt: tomorrow.toISOString().split('T')[0]
  }));
};

// Challenge categories with display info
export const challengeCategories = {
  photography: {
    name: 'Photography',
    icon: '📸',
    color: 'bg-purple-500/10 text-purple-500'
  },
  maintenance: {
    name: 'Maintenance',
    icon: '🔧',
    color: 'bg-blue-500/10 text-blue-500'
  },
  community: {
    name: 'Community',
    icon: '👥',
    color: 'bg-green-500/10 text-green-500'
  },
  knowledge: {
    name: 'Knowledge',
    icon: '🧠',
    color: 'bg-orange-500/10 text-orange-500'
  },
  adventure: {
    name: 'Adventure',
    icon: '🗺️',
    color: 'bg-red-500/10 text-red-500'
  }
};

// Difficulty levels with display info
export const difficultyLevels = {
  easy: {
    name: 'Easy',
    icon: '⭐',
    color: 'bg-green-500/10 text-green-500'
  },
  medium: {
    name: 'Medium',
    icon: '⭐⭐',
    color: 'bg-yellow-500/10 text-yellow-500'
  },
  hard: {
    name: 'Hard',
    icon: '⭐⭐⭐',
    color: 'bg-red-500/10 text-red-500'
  }
};